title: Open Source Haven
author: Example360
email: bestmathmachine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where you will witness a haven of open source program projects, development, encouragement, and more.
  This is an example blog - Feel free to create your own!
  (Note: My real GitHub username is JavascriptLearner815, and email deanlovesmargie@gmail.com.)

# social links
twitter_username: DeanSummer3 # DO NOT include the @ character, or else the build will fail!
github_username:  Example360 # DO NOT include the @ character, or else the build will fail!
youtube_username: SpeedoThreeSixty # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
